/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App1 {
    public String getGreeting() {
        return "Hello world1213.";
    }

    public static void main(String[] args) {
        System.out.println(new App1().getGreeting());
    }
}
